#65 add CRUD for transport
IT-Academy-Social-Projects-KRV/EasyCA-ASP.NET pull request #20
Opened 2021-08-28 14:39 UTC by LizaShemetovska

2021-08-28 14:58 UTC, SashaKorniichuk requested changes

2021-08-28 14:58 UTC, SashaKorniichuk commented on AccountService.Domain/Services/TransportService.cs
> +        private readonly ApplicationDbContext _context;
Add empty line

2021-08-28 15:06 UTC, SashaKorniichuk approved these changes

2021-08-29 09:13 UTC, ICHTLAY approved these changes

2021-08-30 10:23 UTC, pinkevmladchy approved these changes

2021-08-30 10:23 UTC, pinkevmladchy commented on AccountService.Domain/Properties/Resources.resx
> +    <value>Автомобіль не знайден</value>
add "o"

2021-08-30 10:24 UTC, vladtymo approved these changes

2021-08-30 10:25 UTC, merged