#63 Create fluent Validators for entities
IT-Academy-Social-Projects-KRV/EasyCA-ASP.NET pull request #29
Opened 2021-09-01 16:57 UTC by DenysMatiushko293

2021-09-01 19:50 UTC, SashaKorniichuk requested changes

2021-09-01 19:50 UTC, SashaKorniichuk commented on AccountService.Domain/ApiModel/Validators/AddressValidator.cs
> +            if (Regex.IsMatch(country, countryPattern)) return true;
if(...)
{
return true;
}
return false;

2021-09-01 19:50 UTC, SashaKorniichuk commented on AccountService.Domain/ApiModel/Validators/AddressValidator.cs
> +        public static bool IsValidCountry(string country)
add empty lines

2021-09-01 19:50 UTC, SashaKorniichuk commented on AccountService.Domain/ApiModel/Validators/DriverLicenseValidator.cs
> +            foreach (string item in authorities)
You must using authorities.Where(...).Count();

2021-09-01 19:50 UTC, SashaKorniichuk commented on AccountService.Domain/ApiModel/Validators/PersDataValidator.cs
> +            if (((birthday.Year > (today.Year - 75)) && (birthday.Year < (today.Year - 16)) && ((birthday.Month >= 1) && (birthday.Month <= 12))) && ((birthday.Day >= 1) && (birthday.Day <= 31))) ret
Magic number,maybe use const

2021-09-02 09:45 UTC, DenysMatiushko293 reviewed
requested changed are made

2021-09-02 10:31 UTC, LizaShemetovska approved these changes

2021-09-02 10:32 UTC, pinkevmladchy approved these changes

2021-09-02 12:46 UTC, vladtymo requested changes

2021-09-02 12:46 UTC, vladtymo commented on AccountService.Data/Entities/DriverLicense.cs
>  }
Add a newline to the end

2021-09-02 12:46 UTC, vladtymo commented on AccountService.Domain/ApiModel/Validators/DriverLicenseValidator.cs
> +                ((expirationDate.ToUniversalTime().Day - today.ToUniversalTime().Day) <= 0))
This check doesn't work! The DateTime struct has operator < >. You might use them instead.
For example: `if (expirationDate > today)` ...

2021-09-02 12:46 UTC, vladtymo commented on AccountService.Domain/ApiModel/Validators/DriverLicenseValidator.cs
> +            if (count == 1)
You can simplify this code by using the Contains() method
```suggestion

            if (authorities.Contains(issuedBy))
```

2021-09-02 12:46 UTC, vladtymo commented on AccountService.Domain/ApiModel/Validators/InsuaranceValidator.cs
> +            if (count > 0)
Use Contains() method instead

2021-09-02 12:46 UTC, vladtymo commented on AccountService.Domain/ApiModel/Validators/PersDataValidator.cs
> +            if (((birthday.Year > (today.Year - 83)) && (birthday.Year < (today.Year - 14)) && ((birthday.Month >= 1) && (birthday.Month <= 12))) && ((birthday.Day >= 1) && (birthday.Day <= 31)))
Remove the month and day checks, because the DateTime already has them

2021-09-02 12:46 UTC, vladtymo commented on AccountService.Domain/ApiModel/Validators/TransportCategoryValidator.cs
> +            if (count > 0)
You can simplify this code. As a previously you might use Contains

2021-09-02 12:46 UTC, vladtymo commented on AccountService.Domain/ApiModel/Validators/UserValidator.cs
> +            {
You should remove this else operator to avoid the cascading structure

2021-09-02 12:46 UTC, vladtymo commented on AccountService.Domain/ApiModel/Validators/UserValidator.cs
> +        public static bool Ismatching(string firstName)
Rename this method according to the PascalCase convention

2021-09-02 12:46 UTC, vladtymo commented on AccountService.Domain/ApiModel/Validators/DriverLicenseValidator.cs
> +            }
Why don't you use the existing TransportCategoryValidator class in order to avoid code duplication

2021-09-02 16:58 UTC, closed without merging

2021-09-02 16:58 UTC, DenysMatiushko293 commented
New pull request was created in new branch