#78 Create endpoint CreatePersonalData and fix UpdateData
IT-Academy-Social-Projects-KRV/EasyCA-ASP.NET pull request #30
Opened 2021-09-01 17:41 UTC by pinkevmladchy

2021-09-01 18:39 UTC, SashaKorniichuk requested changes

2021-09-01 18:39 UTC, SashaKorniichuk commented on AccountService.Domain/Services/ServiceAccount.cs
> +            var mappedUser = _mapper.Map<User>(data);
You never use this line

2021-09-01 18:39 UTC, SashaKorniichuk commented on AccountService.Domain/Services/ServiceAccount.cs
Where you update Email,FirstName and LastName,you only update a personalData

2021-09-02 10:09 UTC, LizaShemetovska approved these changes

2021-09-02 10:11 UTC, ICHTLAY approved these changes

2021-09-02 10:18 UTC, merged