fix mapper
IT-Academy-Social-Projects-KRV/EasyCA-ASP.NET pull request #36
Opened 2021-09-04 09:59 UTC by pinkevmladchy

2021-09-04 14:08 UTC, SashaKorniichuk requested changes

2021-09-04 14:08 UTC, SashaKorniichuk commented on AccountService.Domain/Services/ServiceAccount.cs
> +            user.UserName = data.Email;
Create Map for UserRequestModel

2021-09-06 11:39 UTC, ICHTLAY approved these changes

2021-09-06 17:16 UTC, SashaKorniichuk approved these changes

2021-09-06 17:19 UTC, merged