#144 Create methods to find euro protocols for view
IT-Academy-Social-Projects-KRV/EasyCA-ASP.NET pull request #73
Opened 2021-10-08 12:39 UTC by aliquispassim

2021-10-09 09:40 UTC, SashaKorniichuk approved these changes

2021-10-09 11:50 UTC, ICHTLAY requested changes

2021-10-09 11:50 UTC, ICHTLAY commented on CrudMicroservice.Domain/ApiModel/ResponseApiModels/EuroProtocolFullResponseModel.cs
> +        public EuroProtocolSimpleResponseModel EuroProtocolSimple { get; set; }
it should contain 'EuroProtocolResponseModel', not 'EuroProtocolSimpleResponseModel', and property should be named just as 'EuroProtocol'

2021-10-09 11:50 UTC, ICHTLAY commented on CrudMicroservice.Domain/ApiModel/ResponseApiModels/EuroProtocolFullResponseModel.cs
> +        public IEnumerable<Witness> Witnesses { get; set; }
it should contain 'IEnumerable<WitnessResponseModel>', not 'IEnumerable<Witness>'

2021-10-09 11:50 UTC, ICHTLAY commented on CrudMicroservice.Domain/Services/EuroProtocolService.cs
> +            var mappedEuroProtocolSimpleResponseModel = _mapper.Map<EuroProtocolSimpleResponseModel>(euroProtocol);
you should map to EuroProtocolResponseModel, not to EuroProtocolSimpleResponseModel

2021-10-09 13:39 UTC, pinkevmladchy approved these changes
but resolve conversation which detected by Ivan

2021-10-09 15:57 UTC, aliquispassim commented on CrudMicroservice.Domain/ApiModel/ResponseApiModels/EuroProtocolFullResponseModel.cs
> +        public IEnumerable<Witness> Witnesses { get; set; }
okay, but `EuroProtocolResponseModel` already contains `IEnumerable<WitnessResponseModel> Witnesses`. maybe I should remove this field from `EuroProtocolFullResponseModel`?

2021-10-10 13:11 UTC, ICHTLAY approved these changes

2021-10-10 13:50 UTC, merged