#128_create_search_for_transport
IT-Academy-Social-Projects-KRV/EasyCA-ASP.NET pull request #75
Opened 2021-10-11 17:27 UTC by swem-st

2021-10-11 17:50 UTC, SashaKorniichuk requested changes

2021-10-11 17:50 UTC, SashaKorniichuk commented on RabbitMQConfig/ConfigureServicesMassTransit.cs
> +                            configurator.Password("Qwerty211@");
move username and password to Secret file

2021-10-11 17:50 UTC, SashaKorniichuk commented on RabbitMQConfig/Models/Requests/TransportRequestModelRabbitMQ.cs
> +
delete empty line

2021-10-11 17:50 UTC, SashaKorniichuk commented on RabbitMQConfig/Models/Responses/TransportResponseModelRabbitMQ.cs
> +
delete empty line

2021-10-11 17:50 UTC, SashaKorniichuk commented on SearchMicroservice.Domain/Services/SearchService.cs
> +        }
add empty line

2021-10-11 17:50 UTC, SashaKorniichuk commented on SearchMicroservice.Domain/Services/SearchService.cs
> +        private readonly IClientFactory _clientFactory;
add empty line

2021-10-11 17:50 UTC, SashaKorniichuk commented on SearchMicroservice.WebAPI/Controllers/SearchController.cs
> +        }
add empty line

2021-10-11 17:50 UTC, SashaKorniichuk commented on SearchMicroservice.WebAPI/Controllers/SearchController.cs
> +        private readonly ISearchService _searchService;
add empty line

2021-10-12 16:55 UTC, SashaKorniichuk approved these changes

2021-10-12 16:55 UTC, pinkevmladchy approved these changes

2021-10-12 17:10 UTC, ICHTLAY approved these changes

2021-10-12 17:15 UTC, merged