#28 Created JWT and RefreshToken
IT-Academy-Social-Projects-KRV/EasyCA-ASP.NET pull request #8
Opened 2021-08-24 11:56 UTC by zharan96prog

2021-08-24 12:07 UTC, ICHTLAY approved these changes

2021-08-24 14:13 UTC, SashaKorniichuk approved these changes

2021-08-25 10:17 UTC, vladtymo requested changes

2021-08-25 10:17 UTC, vladtymo commented on AccountService.Domain/Services/ServiceAccount.cs
> +                Expires = DateTime.UtcNow.AddMinutes(1),
Move token expires minutes value to config file

2021-08-25 10:17 UTC, vladtymo commented on AccountService.WebApi/Controllers/AccountController.cs
> +                Expires = DateTime.UtcNow.AddDays(7),
Move minutes literal to config file

2021-08-25 10:17 UTC, vladtymo commented on AccountService.Domain/Interfaces/IServiceAccount.cs
> +
Remove empty line

2021-08-25 10:17 UTC, vladtymo commented on AccountService.Domain/RequestModels/RevokeTokenRequest.cs
> +﻿
Remove empty line

2021-08-25 14:20 UTC, pinkevmladchy approved these changes
good job

2021-08-25 14:20 UTC, pinkevmladchy commented on AccountService.Data/Entities/User.cs
> +
delete empty line

2021-08-25 14:23 UTC, merged